name: "Build & Release"

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: [ 3.22.0 ]  # Specify your desired Flutter version
        java: [ 19.0.2 ]     # Specify your desired Java version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can choose other distributions like 'zulu', 'adopt', etc.
          java-version: ${{ matrix.java }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - name: Flutter Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter APK (Profile)
        run: flutter build apk --profile

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/profile/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
